Repository MadhushaPrasad/vue-analog-clock, pull requests merged in 2024-04, with the labels that each got.

#3 WIP: Update readme according to issue #2
  README.md
Labels: documentation, help wanted, good first issue, contribution welcome, 📚 docs, WIP

#5 Update readme according to issue #2 (#3)
  README.md
Labels: documentation, 📚 docs

#6 Github action for publish to NPM #4
  .github/workflows/npm-publish.yml
  README.md
  package.json
Labels: documentation, release, 📚 docs, release-0.0.3

#9 Create npm-publish.yml
  .github/workflows/npm-publish.yml
Labels: release, 📚 docs, release-0.0.3

#14 Version 0.1.0
  README.md
  package-lock.json
  package.json
  src/components/analog-clock/AnalogClock.vue
Labels: enhancement, help wanted, Feature Request, needs-repro, release-0.1.0
